# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: impressions.proto for package 'proto'

require 'grpc'
require 'impressions_pb'

module Proto
  module Impressions
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.Impressions'

      # Gets the most viewed elements in a certain period
      rpc :GetMostViewed, Empty, ViewedResponse
      # Adds an view to the element
      rpc :AddView, AddViewParams, Empty
    end

    Stub = Service.rpc_stub_class
  end
end
