# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: impressions.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("impressions.proto", :syntax => :proto3) do
    add_message "proto.Empty" do
    end
    add_message "proto.AddViewParams" do
      optional :ElementId, :int64, 3
      optional :Language, :string, 1
      optional :ElementType, :string, 2
    end
    add_message "proto.ViewedParams" do
      optional :From, :int64, 1
      optional :Until, :int64, 2
      optional :ElementType, :string, 3
      optional :Language, :string, 4
    end
    add_message "proto.Viewed" do
      optional :Count, :int32, 1
      optional :ElementId, :int32, 2
      optional :Language, :string, 3
    end
    add_message "proto.ViewedResponse" do
      repeated :Items, :message, 1, "proto.Viewed"
    end
  end
end

module Proto
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Empty").msgclass
  AddViewParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.AddViewParams").msgclass
  ViewedParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ViewedParams").msgclass
  Viewed = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Viewed").msgclass
  ViewedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ViewedResponse").msgclass
end
